### ISSUE TITLE
Dataset images are being tracked

### ISSUE THREAD

**Issue by Lukasz825700516** [Lukasz825700516/KPZ-2024-traffic_lights#16]
# Reason

Changes to the training dataset as new images or stuff are inconsequential to us. This repository should only contain the logic behind the usage of this data, and not data itself. 

# Objective

- [x] remove datasets from repository (rebase :fearful:)
- [x] add script pulling the datasets from somewhere (roboflow?)

# Requires

None

**Comment by Lukasz825700516** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Pobierać datasety przy pomocy API zamiast trzymać je w repo](https://trello.com/c/zzmlrGgs/23-pobiera%C4%87-datasety-przy-pomocy-api-zamiast-trzyma%C4%87-je-w-repo)

**Comment by Iamhexi** [comment]
After merging #34, we may close this issue.
