### ISSUE TITLE
Fix class names

### ISSUE THREAD

**Issue by Lukasz825700516** [Lukasz825700516/KPZ-2024-traffic_lights#8]
# Reason

Adult and child classes are swapped.

# Objective

Remove confusion from swapped classes.

**Comment by Lukasz825700516** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Poprawić zamienione nazwy klas przy ludziach](https://trello.com/c/YEojHkqW/15-poprawi%C4%87-zamienione-nazwy-klas-przy-ludziach)

**Comment by Iamhexi** [comment]
More details, please. Which classes are mistakenly swapped?

**Comment by Lukasz825700516** [comment]
@Iamhexi Based on 
https://github.com/Lukasz825700516/KPZ-2024-traffic_lights/blob/34b0cb96066ca6ef4148540931498e4f22b14a53/last_run/val_batch2_pred.jpg 
the current adult class should be child, eldery should be adult, and adult should be eldery
https://github.com/Lukasz825700516/KPZ-2024-traffic_lights/blob/34b0cb96066ca6ef4148540931498e4f22b14a53/Datasets/data.yaml#L2-L4
